// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHLMtFsWNmId0V8Pt8eSes3zvTeRjJbZ4',
    appId: '1:118098998644:web:1895a62c6399fddb6a2821',
    messagingSenderId: '118098998644',
    projectId: 'first-app-jordi',
    authDomain: 'first-app-jordi.firebaseapp.com',
    databaseURL:
        'https://first-app-jordi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-jordi.firebasestorage.app',
    measurementId: 'G-Q2V3J0L84Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBByw7anl-h6Koy7VEV7JGtj1Pgcx8LCAk',
    appId: '1:118098998644:android:77fccf1330bb7fb16a2821',
    messagingSenderId: '118098998644',
    projectId: 'first-app-jordi',
    databaseURL:
        'https://first-app-jordi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-jordi.firebasestorage.app',
  );
}
